function showTab(t){["menu","orders","qr"].forEach(x=>document.getElementById(x+"Tab").classList.toggle("hidden",x!==t));if(t==="menu")renderAdmin();if(t==="orders")renderOrders()}
function renderAdmin(){let d=getData(),el=document.getElementById("adminMenu");el.innerHTML=d.stores.map((s,i)=>`<div class="panel"><h3>${s.icon} <input class="input" value="${s.name}" onchange="renameStore(${i},this.value)"></h3><button onclick="toggleStore(${i})">REMOVE STORE</button><div class="admin-food">${s.foods.map((f,j)=>`<input class="input" value="${f.name}" onchange="editFood(${i},${j},'name',this.value)"><input class="input" type="number" value="${f.price}" onchange="editFood(${i},${j},'price',this.value)"><label><input type="checkbox" ${f.available?'checked':''} onchange="editFood(${i},${j},'available',this.checked)"> Available</label><button onclick="removeFood(${i},${j})">REMOVE</button>`).join("")}</div><button onclick="addFood(${i})">+ ADD FOOD</button></div>`).join("")+`<button onclick="addStore()">+ ADD STORE</button>`}
function renameStore(i,v){let d=getData();d.stores[i].name=v;saveData(d);renderAdmin()}
function toggleStore(i){let d=getData();if(!confirm("Remove this store?"))return;d.stores.splice(i,1);saveData(d);renderAdmin()}
function addStore(){let d=getData();d.stores.push({name:"New Store",icon:"🍽️",foods:[]});saveData(d);renderAdmin()}
function addFood(i){let d=getData();d.stores[i].foods.push({name:"New Food",price:0,choices:[],available:true});saveData(d);renderAdmin()}
function editFood(i,j,k,v){let d=getData();d.stores[i].foods[j][k]=k==="price"?Number(v):v;saveData(d)}
function removeFood(i,j){let d=getData();d.stores[i].foods.splice(j,1);saveData(d);renderAdmin()}
function renderOrders(){let el=document.getElementById("orders"),os=orders();el.innerHTML=os.length?os.map((o,i)=>`<div class="panel"><b>${o.id}</b><p>${o.customer.name} • ${o.customer.phone}</p><p>${o.customer.municipality} • ${o.customer.address}</p><p>Total: ₱${o.total.toFixed(2)} • Delivery: ₱${o.deliveryFee.toFixed(2)}</p><p>${o.items.map(x=>`${x.store}: ${x.food} ×${x.qty} (${x.choices.join(", ")})`).join("<br>")}</p><select onchange="assign(${i},this.value)"><option value="">Assign Rider</option><option ${o.assignedRider==="Rider 1"?"selected":""}>Rider 1</option><option ${o.assignedRider==="Rider 2"?"selected":""}>Rider 2</option></select></div>`).join(""):"<p>No orders yet.</p>"}
function assign(i,v){let os=orders();os[i].assignedRider=v;os[i].status=v?"ASSIGNED":"NEW";saveOrders(os);renderOrders()}
function exportMenu(){let d=getData(),name=prompt("Store name to export:",d.stores[0]?.name||"");let s=d.stores.find(x=>x.name===name)||d.stores[0];document.getElementById("jsonBox").value=JSON.stringify(s)}
function importMenu(){try{let s=JSON.parse(document.getElementById("jsonBox").value),d=getData(),i=d.stores.findIndex(x=>x.name===s.name);if(i>=0)d.stores[i]=s;else d.stores.push(s);saveData(d);renderAdmin();alert("Menu imported.")}catch(e){alert("Invalid menu JSON.")}}
renderAdmin();