const KEY="mhac_v21_data", ORDERKEY="mhac_v21_orders";
const seed={stores:[
{name:"Jollibee",icon:"🍗",foods:[{name:"1pc Chicken",price:99,choices:["No drink","Regular Drink","Medium Drink","Large Drink"],available:true}]},
{name:"McDo",icon:"🍟",foods:[{name:"Burger Solo",price:99,choices:["No drink","Regular Drink","Medium Drink","Large Drink"],available:true}]},
{name:"Mang Inasal",icon:"🍗",foods:[{name:"Chicken Meal",price:129,choices:["No drink","Regular Drink","Medium Drink","Large Drink"],available:true}]},
{name:"KFC",icon:"🍗",foods:[{name:"Chicken Meal",price:119,choices:["No drink","Regular Drink","Medium Drink","Large Drink"],available:true}]},
{name:"Pakpak Haven",icon:"🍗",foods:[
{name:"Unlimited Wings + Unlimited Rice",price:269,choices:["Cheese","Buffalo","Honey Mustard","Korean Sauce","Caramel Patis","Salted Egg","Japanese Garlic Mayo","Honey Garlic","Honey Lemon Glazed","Garlic Parmesan","Chili Cheese"],available:true},
{name:"Unlimited Wings + Unlimited Rice + Unlimited Drinks",price:289,choices:["Cheese","Buffalo","Honey Mustard","Korean Sauce","Caramel Patis","Salted Egg","Japanese Garlic Mayo","Honey Garlic","Honey Lemon Glazed","Garlic Parmesan","Chili Cheese"],available:true},
{name:"Ala Carte 6 pcs",price:169,choices:["1 flavor"],available:true},{name:"Ala Carte 8 pcs",price:209,choices:["1 flavor","2 flavors"],available:true},
{name:"Ala Carte 16 pcs",price:309,choices:["1 flavor","2 flavors","3 flavors"],available:true},{name:"Ala Carte 24 pcs",price:449,choices:["1 flavor","2 flavors","3 flavors","4 flavors"],available:true},
{name:"Ala Carte 36 pcs",price:649,choices:["1 flavor","2 flavors","3 flavors","4 flavors","5 flavors"],available:true},
{name:"Ala Carte 45 pcs",price:749,choices:["1 flavor","2 flavors","3 flavors","4 flavors","5 flavors","6 flavors"],available:true},
{name:"Budget Meal 4 pcs + Rice + Drinks",price:149,choices:["Cheese","Buffalo","Honey Mustard","Korean Sauce","Caramel Patis","Salted Egg","Japanese Garlic Mayo","Honey Garlic","Honey Lemon Glazed","Garlic Parmesan","Chili Cheese"],available:true},
{name:"Budget Meal 8 pcs + Rice + Drinks",price:209,choices:["Cheese","Buffalo","Honey Mustard","Korean Sauce","Caramel Patis","Salted Egg","Japanese Garlic Mayo","Honey Garlic","Honey Lemon Glazed","Garlic Parmesan","Chili Cheese"],available:true},
{name:"Pitcher Juice / Iced Tea / Red Tea / Blue Lemonade",price:60,choices:[],available:true},{name:"Extra Rice",price:20,choices:[],available:true},{name:"Bottled Water",price:20,choices:[],available:true},{name:"Soft Drinks Small",price:25,choices:[],available:true},{name:"Soft Drinks 1.5L",price:110,choices:[],available:true}
]}]};
function getData(){let x=localStorage.getItem(KEY);if(!x){localStorage.setItem(KEY,JSON.stringify(seed));return seed}return JSON.parse(x)}
function saveData(d){localStorage.setItem(KEY,JSON.stringify(d))}
function orders(){return JSON.parse(localStorage.getItem(ORDERKEY)||"[]")}
function saveOrders(x){localStorage.setItem(ORDERKEY,JSON.stringify(x))}
let cart=JSON.parse(sessionStorage.getItem("mhac_cart")||"[]");
function saveCart(){sessionStorage.setItem("mhac_cart",JSON.stringify(cart))}
function renderStores(){let d=getData(),el=document.getElementById("stores");if(!el)return;el.innerHTML=d.stores.map((s,i)=>`<div class="store" onclick="openStore(${i})"><h3>${s.icon} ${s.name}</h3><div class="small">${s.foods.filter(f=>f.available).length} available items</div></div>`).join("")}
function openStore(i){let d=getData(),s=d.stores[i],main=document.querySelector("main");let old=document.getElementById("menuPanel");if(old)old.remove();let sec=document.createElement("section");sec.id="menuPanel";sec.className="panel";sec.innerHTML=`<div class="row"><h2 style="flex:1">${s.icon} ${s.name}</h2><button onclick="document.getElementById('menuPanel').remove()">CLOSE</button></div><div id="foods">${s.foods.map((f,j)=>f.available?`<div class="food" onclick="chooseFood(${i},${j})"><h3>${f.name}</h3><b>₱${f.price.toFixed(2)}</b></div>`:`<div class="food unavailable"><h3>${f.name}</h3><b>UNAVAILABLE</b></div>`).join("")}</div>`;main.insertBefore(sec,document.querySelector(".cart"))}
function chooseFood(si,fi){let d=getData(),f=d.stores[si].foods[fi],panel=document.getElementById("menuPanel");let choices=f.choices||[];let existing=document.getElementById("choicePanel");if(existing)existing.remove();let p=document.createElement("div");p.id="choicePanel";p.className="panel";p.innerHTML=`<h3>${f.name} — ₱${f.price.toFixed(2)}</h3><label>Quantity</label><input id="q" class="input" type="number" min="1" value="1">${choices.length?`<p><b>Choose:</b></p><div class="grid">${choices.map((c,i)=>`<div class="choice" onclick="selectChoice(this,${i})">${c}</div>`).join("")}</div>`:""}<br><button onclick="addItem(${si},${fi})">ADD TO CART</button>`;panel.appendChild(p)}
function selectChoice(el,i){document.querySelectorAll("#choicePanel .choice").forEach(x=>x.classList.remove("selected"));el.classList.add("selected");el.dataset.selected="1"}
function addItem(si,fi){let d=getData(),s=d.stores[si],f=s.foods[fi],q=Math.max(1,Number(document.getElementById("q").value)||1),c=[...document.querySelectorAll("#choicePanel .choice.selected")].map(x=>x.textContent);let storeNames=[...new Set(cart.map(x=>x.store))];if(!storeNames.includes(s.name)&&storeNames.length>=2){document.getElementById("choicePanel").insertAdjacentHTML("afterbegin",`<div class="notice">⚠️ 2 STORES MAXIMUM — You already selected 2 stores.</div>`);return}cart.push({store:s.name,food:f.name,price:f.price,qty:q,choices:c});saveCart();renderCart()}
function renderCart(){let el=document.getElementById("cart"),count=document.getElementById("cartCount");if(!el)return;count.textContent=cart.reduce((a,x)=>a+x.qty,0);if(!cart.length){el.innerHTML="<p>No items yet.</p>";document.getElementById("checkout").innerHTML="";return}let groups={};cart.forEach((x,i)=>(groups[x.store]??=[]).push({...x,i}));el.innerHTML=Object.entries(groups).map(([s,items])=>`<div class="panel"><div class="store-label">${s}</div>${items.map(x=>`<div class="cart-item"><b>${x.food}</b> × ${x.qty}<br><span class="small">${x.choices.join(", ")||"No choices"}</span><br>₱${(x.price*x.qty).toFixed(2)} <button onclick="removeItem(${x.i})">REMOVE</button></div>`).join("")}</div>`).join("");let subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0);let service=subtotal*.10;document.getElementById("checkout").innerHTML=`<div class="panel"><h3>ORDER SUMMARY</h3><p>Food Order: ₱${subtotal.toFixed(2)}</p><p>Service Fee (10%): ₱${service.toFixed(2)}</p><p>Delivery Fee: <b>Customer calculates at checkout</b></p><p class="total">Subtotal before delivery: ₱${(subtotal+service+(Object.keys(groups).length>1?5:0)).toFixed(2)}</p><button onclick="checkout()">PLACE ORDER</button></div>`}
function removeItem(i){cart.splice(i,1);saveCart();renderCart()}
function checkout(){let subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0),service=subtotal*.1,storeCount=new Set(cart.map(x=>x.store)).size;let box=document.getElementById("checkout");box.innerHTML=`<div class="panel"><h3>CUSTOMER INFORMATION</h3><input id="custName" class="input" placeholder="Name"><input id="custPhone" class="input" placeholder="Contact Number"><select id="municipality" class="input"><option value="">Select Municipality</option><option>PANIQUI</option><option>MONCADA</option><option>RAMOS</option><option>GERONA</option><option>PURA</option><option>ANAO</option><option>NAMPICUAN</option></select><input id="address" class="input" placeholder="Barangay / Complete Address"><input id="delivery" class="input" type="number" min="0" placeholder="Calculated Delivery Fee"><p>Food Order: ₱${subtotal.toFixed(2)}</p><p>Service Fee: ₱${service.toFixed(2)}</p><p>Additional Store Fee: ₱${storeCount>1?5:0}</p><button onclick="sendOrder()">SEND ORDER</button></div>`}
function sendOrder(){let name=document.getElementById("custName").value.trim(),phone=document.getElementById("custPhone").value.trim(),mun=document.getElementById("municipality").value,address=document.getElementById("address").value.trim(),df=Number(document.getElementById("delivery").value);if(!name||!phone||!mun||!address||!df){alert("Please complete customer information and delivery fee.");return}let subtotal=cart.reduce((a,x)=>a+x.price*x.qty,0),o={id:"MHAC-"+Date.now(),customer:{name,phone,municipality:mun,address},items:cart,total:subtotal+subtotal*.1+df+(new Set(cart.map(x=>x.store)).size>1?5:0),deliveryFee:df,status:"NEW",assignedRider:""};let os=orders();os.push(o);saveOrders(os);cart=[];saveCart();renderCart();document.getElementById("checkout").innerHTML=`<div class="notice">✅ ORDER SENT SUCCESSFULLY — Order ${o.id}</div>`}
renderStores();renderCart();